### ISSUE TITLE
Indicator for resizable terminal

### ISSUE THREAD

**Issue by tedstoychev** [vlang/playground#50]
The terminal in the playground is resizable. However there is no visual indicator for this. One solution would be to add this CSS style to the border:

```
cursor: row-resize;
```

<details>
  <summary>Example</summary>

  <img width="1280" alt="row-resize" src="https://user-images.githubusercontent.com/1466111/213479885-b021e9b1-967a-4c61-9915-a1d30039be5d.png">
</details>

or:

```
cursor: ns-resize;
```

<details>
  <summary>Example</summary>

  <img width="1280" alt="ns-resize" src="https://user-images.githubusercontent.com/1466111/213480043-e4de5cb7-bd67-447e-8aa0-07c4ab843842.png">
</details>

`row-resize` is used in VS Code and `ns-resize` is used in Chrome Developer Tools. Either one looks OK to me.

**Comment by i582** [comment]
Indeed, thanks for the note!

**Comment by tedstoychev** [comment]
Super. Just to share - for `cursor` there is no need for the `:hover` specifier i.e. this would also work:

```css
.playground__terminal .header {
    cursor: row-resize;
}
```
