### ISSUE TITLE
Move the border with the terminal a little bit lower?

### ISSUE THREAD

**Issue by tedstoychev** [vlang/playground#51]
This is purely aesthetic but may I suggest moving the border with the terminal a little bit lower? For example:

| Before  | After |
| - | - |
| <img width="1392" alt="Before" src="https://user-images.githubusercontent.com/1466111/213488201-31ce40b8-f501-4f23-8330-ad742a58c2be.png">  | <img width="1392" alt="After" src="https://user-images.githubusercontent.com/1466111/213488901-5179e7b4-4b15-4ed9-a87e-07dec4f698df.png">  |

**Comment by i582** [comment]
Indeed, I like how the After looks! Thank you for suggestion!

**Comment by i582** [comment]
By the way, if you want, you can make a couple of small PRs for your suggestions :)
We are always very glad to new contributors!

**Comment by tedstoychev** [comment]
Will try to contribute as much as I can. :)
