### ISSUE TITLE
Could you enable https://play.vlang.io/ allow CORS?

### ISSUE THREAD

**Issue by mokeyish** [vlang/playground#58]
I am developing an obsidian plugin that allow popular languages codeblock in markdown can run directly .

**(This would benefit that users who take notes with Obsidian for learning vlang)**

[The repo of Obsidian Code Emitter](https://github.com/mokeyish/obsidian-code-emitter)

![](https://raw.githubusercontent.com/mokeyish/obsidian-code-emitter/master/screenshots/code-emitter.gif)

**Comment by i582** [comment]
Hi, @mokeyish, you can use https://play.vosca.dev for this purpose
See endpoints here: https://github.com/vlang-association/playground/blob/main/server/README.md

**Comment by mokeyish** [comment]
Thanks! Now it supports vlang.😁

![图片](https://github.com/vlang/playground/assets/16131917/79fdb1a9-af30-4f34-a99f-9c33a38b65ce)
